### ISSUE TITLE
could you please give the data of train and test

### ISSUE THREAD

**Issue by qiu931110** [jrussino/eigen_depth#1]
thanks~！

**Comment by jrussino** [comment]
In the README, there is a link to the research paper that this code is based on. The original authors used the NYU-Depth and KITTI data sets for training & evaluation:
http://cs.nyu.edu/~silberman/datasets/nyu_depth_v2.html
http://www.cvlibs.net/datasets/kitti/
I believe they also did some pre-training on ImageNet (http://www.image-net.org/), at least for some of their comparisons.

I was interested in seeing how well it could predict depth maps for the game DOOM, using the ViZDoom engine (http://vizdoom.cs.put.edu.pl/), which can provide both RGB and depth frames. I captured imagery from the game engine for that purpose, but for logistical & legal reasons I won't be providing that data. I don't think it would be of much use to you anyway.

Note that I did not invent this approach/architecture and had no involvement with the referenced research. I wrote this implementation as an exercise, to see how well I understood the paper and to learn a little bit about Keras. It was never fully completed, so I don't recommend using it (either as a reference or as a tool)! I was able to get it to produce acceptable-looking-to-my-eye depth output for RGB game frames, but never did any kind of formal evaluation.
